
--BEST OF ALL ---- JUNÇÃO DE TODAS AS DE BAIXO
SELECT TOP 200
	DB_NAME(QT.DBID) AS DATABASE_NAME,
	EXECUTION_COUNT ,
	TOTAL_WORKER_TIME ,
	TOTAL_LOGICAL_READS,
	TOTAL_LOGICAL_WRITES,
	TOTAL_WORKER_TIME / EXECUTION_COUNT AS [AVG CPU TIME] ,
	TOTAL_LOGICAL_READS+TOTAL_LOGICAL_WRITES AS [IO_TOTAL],
	QP.QUERY_PLAN,
	--REPLACE (REPLACE(QT.TEXT, char(9), ''), CHAR(13) + CHAR(10), ' ') AS QUERY_TEXT
	QT.TEXT
FROM SYS.DM_EXEC_QUERY_STATS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(QS.PLAN_HANDLE) AS QT
CROSS APPLY SYS.DM_EXEC_QUERY_PLAN (QS.PLAN_HANDLE) AS QP
WHERE 
	EXECUTION_COUNT > 100
	AND QT.TEXT NOT LIKE '%SYS.%'
	AND DB_NAME(QT.DBID) = 'buy4_aas'
ORDER BY 
	[AVG CPU TIME] DESC 
	--, EXECUTION_COUNT DESC
	 --[IO_TOTAL] DESC 


-- BLOCKED QUERIES:

SELECT TOP 200
 [Average Time Blocked] = (total_elapsed_time - total_worker_time) / qs.execution_count
,[Total Time Blocked] = total_elapsed_time - total_worker_time 
,[Execution count] = qs.execution_count
,[Individual Query] = SUBSTRING (REPLACE (REPLACE(QT.TEXT, char(9), ''), CHAR(13) + CHAR(10), ' ') ,qs.statement_start_offset/2, 
         (CASE WHEN qs.statement_end_offset = -1 
            THEN LEN(CONVERT(NVARCHAR(MAX), qt.text)) * 2 
          ELSE qs.statement_end_offset END - qs.statement_start_offset)/2) 
,[Parent Query] = REPLACE(REPLACE(QT.TEXT, char(9), ''), CHAR(13) + CHAR(10), ' ')
--,DatabaseName = DB_NAME(qt.dbid)
FROM sys.dm_exec_query_stats qs
CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) as qt

WHERE 
	EXECUTION_COUNT > 100
	AND QT.TEXT NOT LIKE '%SYS.%'

ORDER BY [Average Time Blocked] DESC;



-- Query 1: Top 10 Total CPU Consuming Queries
SELECT TOP 10
QT.TEXT AS STATEMENT_TEXT,
QP.QUERY_PLAN,
QS.TOTAL_WORKER_TIME AS CPU_TIME
FROM SYS.DM_EXEC_QUERY_STATS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT (QS.SQL_HANDLE) AS QT
CROSS APPLY SYS.DM_EXEC_QUERY_PLAN (QS.PLAN_HANDLE) AS QP
ORDER BY TOTAL_WORKER_TIME DESC


-- Query 2: Top 10 Average CPU Consuming Queries
SELECT TOP 10
TOTAL_WORKER_TIME ,
EXECUTION_COUNT ,
TOTAL_WORKER_TIME / EXECUTION_COUNT AS [AVG CPU TIME] ,
QT.TEXT AS QUERYTEXT
FROM SYS.DM_EXEC_QUERY_STATS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(QS.PLAN_HANDLE) AS QT
ORDER BY QS.TOTAL_WORKER_TIME DESC ;


-- Query 3: Top 10 I/O Intensive Queries
SELECT TOP 10
TOTAL_LOGICAL_READS,
TOTAL_LOGICAL_WRITES,
EXECUTION_COUNT,
TOTAL_LOGICAL_READS+TOTAL_LOGICAL_WRITES AS [IO_TOTAL],
QT.TEXT AS QUERY_TEXT,
DB_NAME(QT.DBID) AS DATABASE_NAME,
QT.OBJECTID AS OBJECT_ID
FROM SYS.DM_EXEC_QUERY_STATS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SQL_HANDLE) QT
WHERE TOTAL_LOGICAL_READS+TOTAL_LOGICAL_WRITES > 0
ORDER BY [IO_TOTAL] DESC 


-- Query 4: Execution Count of Each Query
SELECT QS.EXECUTION_COUNT,
QT.TEXT AS QUERY_TEXT,
QT.DBID,
DBNAME= DB_NAME (QT.DBID),
QT.OBJECTID,
QS.TOTAL_ROWS,
QS.LAST_ROWS,
QS.MIN_ROWS,
QS.MAX_ROWS
FROM SYS.DM_EXEC_QUERY_STATS AS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(QS.SQL_HANDLE) AS QT
ORDER BY QS.EXECUTION_COUNT DESC